TOP_300_CLUBS = [
    # España
    "Real Madrid", "Barcelona", "Atlético Madrid", "Athletic Club", "Real Sociedad",
"Sevilla", "Valencia", "Villarreal", "Real Betis", "Celta de Vigo",
"Espanyol", "Getafe", "Rayo Vallecano", "Osasuna", "Mallorca",
"Deportivo Alavés", "Granada", "Las Palmas", "Leganés", "Levante",
"Real Valladolid", "Sporting Gijón", "Real Zaragoza", "Racing Santander",
"Elche", "Tenerife", "Eibar", "Huesca", "Oviedo",
"Mirandés", "Burgos", "Cartagena", "Albacete", "Andorra",
"Alcorcón", "Eldense", "Amorebieta", "Castellón", "Córdoba",
"Deportivo La Coruña", "Málaga", "Numancia", "Murcia", "Ponferradina",
"Recreativo de Huelva", "Hércules", "Cádiz", "Girona", "Almería",

    # Inglaterra
    "Manchester City", "Manchester United", "Liverpool", "Arsenal", "Chelsea",
"Tottenham Hotspur", "Newcastle United", "Aston Villa", "West Ham United", "Brighton & Hove Albion",
"Crystal Palace", "Fulham", "Brentford", "Everton", "Nottingham Forest",
"Wolverhampton Wanderers", "Leicester City", "Southampton", "Leeds United", "Burnley",
"Sunderland", "West Bromwich Albion", "Stoke City", "Middlesbrough", "Coventry City",
"Sheffield Wednesday", "Sheffield United", "Birmingham City", "Derby County", "Blackburn Rovers",
"Preston North End", "Cardiff City", "Swansea City", "Bristol City", "Hull City",
"Queens Park Rangers", "Watford", "Norwich City", "Ipswich Town", "Portsmouth",
"Millwall", "Huddersfield Town",

    # Italia
    "Juventus", "Inter Milan", "AC Milan", "Roma", "Lazio",
"Napoli", "Atalanta", "Fiorentina", "Torino", "Bologna",
"Genoa", "Sampdoria", "Udinese", "Cagliari", "Verona",
"Empoli", "Parma", "Palermo", "Sassuolo", "Monza",
"Venezia", "Brescia", "SPAL", "Pisa", "Como",
"Reggina", "Cosenza", "Frosinone", "Lecce", "Cremonese",
"Ascoli", "Modena", "Ternana", "Bari", "Catanzaro",
"Cesena", "Avellino", "Salernitana", "Spezia", "Mantova",
"Triestina", "Vicenza", "Perugia", "Chievo Verona", "Livorno"
,

    # Alemania
    "Bayern Munich", "Borussia Dortmund", "RB Leipzig", "Bayer Leverkusen", "Borussia Mönchengladbach",
"Eintracht Frankfurt", "VfB Stuttgart", "Werder Bremen", "Hamburger SV", "Schalke 04",
"Hertha Berlin", "Union Berlin", "Freiburg", "Mainz 05", "Augsburg",
"VfL Wolfsburg", "Hoffenheim", "Fortuna Düsseldorf", "Hannover 96", "Köln",
"St. Pauli", "Greuther Fürth", "Holstein Kiel", "Arminia Bielefeld", "Karlsruher SC",
"1. FC Nürnberg", "Darmstadt 98", "Paderborn", "Magdeburg", "Eintracht Braunschweig",
"MSV Duisburg", "Rot-Weiss Essen", "Alemannia Aachen", "1860 Munich", "Kaiserslautern",
"Chemnitzer FC", "Dynamo Dresden", "Hansa Rostock", "Erzgebirge Aue", "Viktoria Köln"
,

    # Francia
    "Paris Saint-Germain", "Olympique de Marseille", "Olympique Lyonnais", "AS Monaco", "Lille",
"Stade Rennais", "Nice", "Lens", "Saint-Étienne", "Nantes",
"Bordeaux", "Toulouse", "Montpellier", "Strasbourg", "Reims",
"Metz", "Brest", "Clermont Foot", "Le Havre", "Auxerre",
"Caen", "Amiens", "Dijon", "Guingamp", "Grenoble",
"Valenciennes", "Sochaux", "Nancy", "Red Star", "Paris FC",
"Ajaccio", "Bastia", "Châteauroux", "Niort", "Orléans",
"Quevilly-Rouen", "Annecy", "Pau FC", "Rodez", "Tours",

    # Portugal & Paises Bajos & Belgica
    "Benfica", "Porto", "Sporting CP", "Braga", "Vitória Guimarães",
"Boavista", "Estoril Praia", "Casa Pia", "Rio Ave", "Famalicão",
"Farense", "Portimonense", "Santa Clara", "Marítimo", "Tondela",
"Arouca", "Moreirense", "Vizela",
"Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar", "Twente",
"Utrecht", "Heerenveen", "Groningen", "Vitesse", "Sparta Rotterdam",
"NEC Nijmegen", "Fortuna Sittard", "RKC Waalwijk", "Go Ahead Eagles",
"Heracles Almelo", "Excelsior", "Cambuur", "PEC Zwolle",
"Anderlecht", "Club Brugge", "Standard Liège", "Genk", "Gent",
"Charleroi", "KV Mechelen", "Cercle Brugge", "Kortrijk", "Oostende",
"St. Truiden", "Eupen", "Westerlo", "Union Saint-Gilloise",
"Royal Antwerp", "Lommel SK", "Beerschot", "RFC Seraing"
,
    
    # Turquia & Grecia & Escocia & Resto de Europa
    "Celtic", "Rangers", "Aberdeen", "Hearts", "Hibernian",
"Dundee United", "Motherwell", "St. Johnstone", "Kilmarnock", "Livingston",
"Dinamo Zagreb", "Hajduk Split", "Rijeka", "Osijek", "Lokomotiva Zagreb",
"Red Star Belgrade", "Partizan Belgrade", "Vojvodina", "Čukarički", "Radnički Niš",
"Shakhtar Donetsk", "Dynamo Kyiv", "Dnipro", "Zorya Luhansk", "Metalist Kharkiv",
"Zenit St. Petersburg", "CSKA Moscow", "Spartak Moscow", "Lokomotiv Moscow", "Dynamo Moscow",
"Rubin Kazan", "Krasnodar", "Rostov", "Ural Yekaterinburg", "Sochi",
"Galatasaray", "Fenerbahçe", "Beşiktaş", "Trabzonspor", "Başakşehir",
"Bursaspor", "Konyaspor", "Sivasspor", "Gaziantep FK", "Adana Demirspor",
"Panathinaikos", "Olympiacos", "AEK Athens", "PAOK", "Aris Thessaloniki",
"Apollon Smyrnis", "OFI Crete", "Asteras Tripolis", "Atromitos", "Volos NFC",
"Slavia Prague", "Sparta Prague", "Viktoria Plzeň", "Bohemians 1905", "Sigma Olomouc",
"Slovan Bratislava", "Trnava", "Žilina", "Dunajská Streda", "Tatran Prešov",
"Basel", "Young Boys", "Grasshoppers", "FC Zürich", "St. Gallen",
"Lugano", "Lausanne-Sport", "Servette", "Thun", "Winterthur",
"Rapid Wien", "Austria Wien", "Sturm Graz", "LASK Linz", "Wolfsberger AC",
"Salzburg", "Admira Wacker", "Ried", "Mattersburg", "Hartberg",
"Legia Warsaw", "Lech Poznań", "Wisła Kraków", "Górnik Zabrze", "Śląsk Wrocław",
"Jagiellonia Białystok", "Pogoń Szczecin", "Cracovia", "Zagłębie Lubin", "Korona Kielce",
"Ferencváros", "MTK Budapest", "Újpest", "Debrecen", "Videoton",
"Honvéd", "Győr", "Paks", "Kecskemét", "Zalaegerszeg",
"Dinamo Minsk", "BATE Borisov", "Shakhtyor Soligorsk", "Torpedo-BelAZ", "Neman Grodno",
"APOEL Nicosia", "Omonia Nicosia", "Anorthosis Famagusta", "AEL Limassol", "Aris Limassol",
"Dinamo Tbilisi", "Saburtalo", "Dila Gori", "Torpedo Kutaisi", "Samtredia",
"Qarabağ", "Neftçi Baku", "Gabala", "Zira", "Sabail",
"Astana", "Kairat Almaty", "Shakhter Karagandy", "Ordabasy", "Tobol Kostanay",
"Molde", "Rosenborg", "Vålerenga", "Brann", "Bodø/Glimt",
"IFK Göteborg", "AIK", "Djurgården", "Malmö FF", "Hammarby",
"Elfsborg", "Norrköping", "Örebro", "Kalmar FF", "Helsingborg",
"FC Copenhagen", "Brøndby IF", "Midtjylland", "Aalborg BK", "Odense BK",
"Silkeborg IF", "Randers FC", "Esbjerg fB", "Vejle BK", "Lyngby BK",
"Dinamo București", "Steaua București (FCSB)", "CFR Cluj", "Universitatea Craiova", "Rapid București",
"Petrolul Ploiești", "Viitorul Constanța", "Politehnica Iași", "Gaz Metan Mediaș", "UTA Arad",
"Maribor", "Olimpija Ljubljana", "Domžale", "Celje", "Koper",
"Željezničar Sarajevo", "Sarajevo", "Zrinjski Mostar", "Borac Banja Luka", "Široki Brijeg",
"Dinamo Tirana", "Partizani Tirana", "KF Tirana", "Skënderbeu Korçë", "Vllaznia Shkodër",
"Shkëndija", "Vardar", "Rabotnički", "Renova", "Sileks",
"Flora Tallinn", "Levadia Tallinn", "Paide Linnameeskond", "Nõmme Kalju", "Tammeka",
"Riga FC", "RFS", "Ventspils", "Liepāja", "Jelgava",
"Žalgiris Vilnius", "Sūduva", "Kauno Žalgiris", "Panevėžys", "Atlantas",

    # Conmebol (Sudamérica)
    "Boca Juniors", "River Plate", "Independiente", "Racing Club", "San Lorenzo",
"Estudiantes LP", "Vélez Sarsfield", "Newell's Old Boys", "Rosario Central",
"Argentinos Juniors", "Huracán", "Lanús", "Banfield", "Gimnasia LP",
"Talleres", "Colón", "Unión", "Godoy Cruz", "Atlético Tucumán", "Patronato",
"Flamengo", "Palmeiras", "Corinthians", "São Paulo", "Santos",
"Grêmio", "Internacional", "Atlético Mineiro", "Cruzeiro", "Botafogo",
"Fluminense", "Vasco da Gama", "Bahia", "Vitória", "Sport Recife",
"Ceará", "Fortaleza", "Chapecoense", "Red Bull Bragantino", "América Mineiro",
"Paraná", "Coritiba", "Juventude", "Paysandu", "Remo",
"Peñarol", "Nacional", "Defensor Sporting", "Danubio", "Liverpool Montevideo",
"River Plate Montevideo", "Cerro", "Rampla Juniors", "Plaza Colonia", "Boston River",
"Colo-Colo", "Universidad de Chile", "Universidad Católica", "Unión Española",
"Audax Italiano", "Palestino", "Huachipato", "Cobresal", "Coquimbo Unido",
"Deportes La Serena", "O'Higgins", "Curicó Unido", "Magallanes", "Santiago Morning",
"Atlético Nacional", "Millonarios", "Independiente Medellín", "Junior",
"Deportivo Cali", "América de Cali", "Once Caldas", "Santa Fe", "Envigado",
"Boyacá Chicó", "La Equidad", "Deportes Tolima", "Atlético Bucaramanga",
"Cúcuta Deportivo", "Pasto", "Unión Magdalena", "Alianza Petrolera", "Patriotas",
"LDU Quito", "Barcelona SC", "Emelec", "El Nacional", "Deportivo Quito",
"Aucas", "Macará", "Olmedo", "Mushuc Runa", "Orense",
"Sporting Cristal", "Alianza Lima", "Universitario", "Cienciano", "Melgar",
"Sport Boys", "Municipal", "UTC Cajamarca", "Carlos Mannucci", "Ayacucho FC",
"Bolívar", "The Strongest", "Oriente Petrolero", "Blooming", "Wilstermann",
"Royal Pari", "Always Ready", "Nacional Potosí", "Guabirá", "Real Santa Cruz",
"Olimpia Asunción", "Cerro Porteño", "Libertad", "Guaraní", "Sol de América",
"Sportivo Luqueño", "General Díaz", "Nacional Asunción", "River Plate Asunción",
"3 de Febrero", "Sportivo Trinidense", "Atlético Venezuela", "Caracas FC",
"Deportivo Táchira", "Zamora FC", "Mineros de Guayana", "Estudiantes de Mérida",
"Aragua FC", "Portuguesa FC", "Monagas SC", "Trujillanos", "Atlético El Vigía",
"Universitario de Sucre", "Real Potosí", "San José Oruro", "Petrolero Yacuiba",
"Sport Loreto", "Juan Aurich", "León de Huánuco", "Alianza Atlético", "Defensor La Bocana",
"Atlético Huila", "Cortuluá", "Atlético FC", "Real Cartagena", "Valledupar FC",
"Bogotá FC", "Tigres FC", "Barranquilla FC", "Fortaleza CEIF", "Llaneros",
"Deportivo Cuenca", "Técnico Universitario", "Liga de Loja", "Manta FC", "Fuerza Amarilla",
"Deportivo Quito B", "Imbabura SC", "Deportivo Azogues", "Deportivo Quevedo", "Espoli",
"Club Aurora", "Universitario de Sucre", "Real Mamoré", "La Paz FC", "Destroyers",
"Club Independiente Petrolero", "Atlético Palmaflor", "Club Stormers", "Club Bata", "Club Litoral",
"Club San José", "Club Unión Central", "Club Wilstermann B", "Club Real Beni", "Club 24 de Septiembre",
"Club Rubio Ñu", "Club Presidente Hayes", "Club Tacuary", "Club Fernando de la Mora", "Club Resistencia",
"Club Sportivo San Lorenzo", "Club Deportivo Capiatá", "Club Martín Ledesma", "Club Colegiales", "Club Cristóbal Colón",
"Club Sportivo Iteño", "Club Olimpia Itá", "Club Sportivo Carapeguá", "Club Sportivo Ameliano", "Club Sportivo Yegros",
"Club Sportivo Limpeño", "Club Sportivo Benjamín Aceval", "Club Sportivo Trinidense B", "Club Sportivo Luqueño B", "Club Sportivo Encarnación",
"Club Deportivo Santaní", "Club Deportivo Caaguazú", "Club Deportivo Caacupé", "Club Deportivo San Pedro", "Club Deportivo Itapúa",
"Club Deportivo Paraguarí", "Club Deportivo Misiones", "Club Deportivo Ñeembucú", "Club Deportivo Guairá", "Club Deportivo Concepción",

    # Concacaf (Norte y Centroamérica)
   "America", "Cruz Azul", "Monterrey", "Tigres", "Chivas", "Pachuca", "Pumas UNAM",
"Leon", "Toluca", "Atlas", "Santos Laguna", "Tijuana", "Necaxa", "Querétaro",
"San Luis", "Mazatlán", "Juárez", "Dorados", "Leones Negros", "Atlante",
"Inter Miami", "Los Angeles FC", "LA Galaxy", "Seattle Sounders", "Columbus Crew",
"Philadelphia Union", "FC Cincinnati", "New York City FC", "Atlanta United",
"Orlando City", "Portland Timbers", "Chicago Fire", "Houston Dynamo",
"San Jose Earthquakes", "Real Salt Lake", "Minnesota United", "Austin FC",
"St. Louis City", "Nashville SC", "Colorado Rapids", "New England Revolution",
"D.C. United", "Toronto FC", "CF Montréal", "Vancouver Whitecaps", "Forge FC",
"Cavalry FC", "Pacific FC", "York United", "Atlético Ottawa", "Valour FC",
"Saprissa", "Alajuelense", "Herediano", "Cartaginés", "San Carlos", "Pérez Zeledón",
"Grecia", "Sporting San José", "Olimpia", "Motagua", "Real España", "Marathón",
"Victoria", "Vida", "Comunicaciones", "Municipal", "Antigua GFC", "Xelajú MC",
"Malacateco", "Cobán Imperial", "Tauro FC", "Plaza Amador", "Árabe Unido",
"Independiente CAI", "San Francisco FC", "Costa del Este", "Santa Gema",
"Alianza FC", "FAS", "Águila", "Metapán", "Firpo", "Chalatenango",
"Diriangén", "Walter Ferretti", "Real Estelí", "Managua FC", "Juventus Managua",
"Belmopan Bandits", "Verdes FC", "San Pedro Pirates", "Wagiya", "Police United",
"Mount Pleasant FA", "Arnett Gardens", "Harbour View", "Waterhouse", "Tivoli Gardens",
"Portmore United", "Cavalier SC", "Defence Force", "W Connection", "Central FC",
"Club Sando", "Point Fortin", "St. Ann’s Rangers", "Cibao FC", "Atlético Pantoja",
"Moca FC", "O&M FC", "Jarabacoa FC", "Atlantico FC", "Don Bosco", "Violette AC",
"Racing Club Haití", "Tempête FC", "Cavaly AS", "Baltimore SC", "Florencio FC",
"Bayamón FC", "Puerto Rico Sol", "Mayagüez FC", "Guaynabo Fluminense", "Metropolitan FA",
"Inter Moengotapoe", "Robinhood", "Leo Victor", "Transvaal", "Walking Boyz Company",
"SV Notch", "SV Excelsior", "SV Voorwaarts", "SV Nishan 42", "SV Cosmos",

    # Asia y África
    "Al Ahly", "Zamalek", "Pyramids FC", "Ismaily", "Al Masry",
"Wydad Casablanca", "Raja Casablanca", "FAR Rabat", "Maghreb Fès", "Hassania Agadir",
"Esperance Tunis", "Club Africain", "Étoile du Sahel", "CS Sfaxien", "US Monastir",
"Kaizer Chiefs", "Orlando Pirates", "Mamelodi Sundowns", "SuperSport United", "Bidvest Wits",
"TP Mazembe", "AS Vita Club", "DC Motema Pembe", "St. Eloi Lupopo", "Maniema Union",
"Enyimba", "Kano Pillars", "Rangers International", "Shooting Stars", "Plateau United",
"Al Hilal Omdurman", "Al-Merrikh", "KCCA FC", "Vipers SC", "SC Villa",
"APR FC", "Rayon Sports", "Young Africans", "Simba SC", "Azam FC",
"ASEC Mimosas", "Africa Sports", "Stade d’Abidjan", "Williamsville AC", "SOA",
"Horoya AC", "Hafia FC", "AS Kaloum", "Ashanti Kotoko", "Hearts of Oak",
"Stade Malien", "Djoliba AC", "AS Real Bamako", "JS Kabylie", "USM Alger",
"MC Alger", "CR Belouizdad", "ES Sétif", "NA Hussein Dey", "Paradou AC",

"Al Hilal Riyadh", "Al Nassr", "Al Ittihad Jeddah", "Al Shabab", "Al Fateh",
"Al Ain", "Al Wahda Abu Dhabi", "Al Jazira", "Sharjah FC", "Shabab Al Ahli",
"Persepolis", "Esteghlal", "Sepahan", "Tractor", "Foolad",
"Al Sadd", "Al Duhail", "Al Arabi", "Al Rayyan", "Al Wakrah",
"Pakhtakor", "Bunyodkor", "Nasaf Qarshi", "Lokomotiv Tashkent", "AGMK",
"Al Kuwait SC", "Al Qadsia", "Kazma SC", "Al Salmiya", "Al Arabi Kuwait",
"Johor Darul Ta’zim", "Selangor FA", "Kedah FA", "Pahang FA", "Perak FA",
"Buriram United", "Muangthong United", "BG Pathum United", "Chonburi FC", "Bangkok United",
"Persija Jakarta", "Persib Bandung", "Arema FC", "Persebaya Surabaya", "PSM Makassar",
"Vietnam Hanoi FC", "Ho Chi Minh City FC", "Than Quang Ninh", "Becamex Binh Duong", "Da Nang FC",
"Shanghai SIPG", "Guangzhou Evergrande", "Beijing Guoan", "Shandong Taishan", "Wuhan Three Towns",
"Kashima Antlers", "Urawa Red Diamonds", "Yokohama F. Marinos", "Kawasaki Frontale", "Gamba Osaka",
"FC Tokyo", "Nagoya Grampus", "Cerezo Osaka", "Sanfrecce Hiroshima", "Shimizu S-Pulse",
"Jeonbuk Hyundai Motors", "Ulsan Hyundai", "FC Seoul", "Pohang Steelers", "Suwon Samsung Bluewings",

"Sydney FC", "Melbourne Victory", "Melbourne City", "Brisbane Roar", "Adelaide United",
"Perth Glory", "Western Sydney Wanderers", "Central Coast Mariners", "Newcastle Jets", "Wellington Phoenix",
"Auckland City", "Waitakere United", "Team Wellington", "Canterbury United", "Southern United",
"Ba FC", "Suva FC", "Rewa FC", "Labasa FC", "Nadi FC",
"Hekari United", "Lae City Dwellers", "Madang FC", "Toti City FC", "Oro FC"

]
